### ISSUE TITLE
failed login

### ISSUE THREAD

**Issue by ookangzheng** [mitchellurgero/pivpn-gui#1]
I'm using pivpn, ubuntu 16.04.
what is the login name and password?

**Comment by mitchellurgero** [comment]
The same as any sudo user...

**Comment by Scott1974-1** [comment]
it won't let me login using my pi account.. it just says incorrect username or password. then after a bunch of attempts it says too many attempts contact you system administrator. I'm having the same issue with OpenRSD as well...

any help would be great.

thanks

**Comment by mitchellurgero** [comment]
IS apache running as pi, and is sudo password disabled for that user.

**Comment by Scott1974-1** [comment]
Yes. All that was done and checked


----
Scott Bremner
SBS Computer Logistics Ltd. 
scottbremner@gmail.com

**Comment by mitchellurgero** [comment]
Can you give me the last view lines of /var/log/apache2/error.log?

**Comment by Scott1974-1** [comment]
there is nothing in the error.log file.. its empty

**Comment by Scott1974-1** [comment]
ok. I got past the login error. it was lighttpd that was causing the issue so I removed it and am now using apache2 as the web server.

now I can login with pi but once its logged in all I see is a spinning loading dots and I can't select anything.

**Comment by Scott1974-1** [comment]
it seems to be working finally after I did a apt-get update.

thanks for your help.
great app.

**Comment by Scott1974-1** [comment]
also on the main dashboard page of openrsd under the updates area there is a spelling error...

There was an error checking for OepnRSD updates.

it should say OpenRSD not OepnRSD

**Comment by maxgrass** [comment]
Running apache/nginx as sudo is a dirty workaround and a security breach as already mentioned in another issues.

**Comment by mitchellurgero** [comment]
It is also mentioned in the readme. of course it is a security issue. However! If the pi is not internet accessible then the security risk goes down SO MUCH.

**Comment by mitchellurgero** [comment]
Also in OpenRSD I am currently working on a way to prompt user for sudo password instead of just allowing all commands in sudo. for better security.
