### ISSUE TITLE
Create new profile with password (don't use [nopass] option)

### ISSUE THREAD

**Issue by nquick** [mitchellurgero/pivpn-gui#2]
Hi, 

Great product and makes setting up and monitoring VPN much easier. Is it possible to change the create new profile so that it asks for a password rather than with the [nopass] option?

Thanks

**Comment by mitchellurgero** [comment]
That was eventually the plan, and maybe in the near future, to create a profile w/ a cert login and a password, just do it over ssh for now. Although not best practice, cert login w/o a password is sufficient for *most* needs. Profiles created over ssh are also monitored with the web-ui. Cheers!
