### ISSUE TITLE
Is it possible to run the Pi VPN GUI using lighttpd?

### ISSUE THREAD

**Issue by polleke67** [mitchellurgero/pivpn-gui#4]
I am running Pi-Hole on the same RPi 1b, and it is using lighttpd.
Apache seems to be too heavy for RPi 1b
Is it possible to run the Pi VPN GUI using lighttpd?
If so, how?

**Comment by mitchellurgero** [comment]
It should be possible, Experiment with it. Follow the instructions but adapt them to lighttpd.

**Comment by nclmrc** [comment]
There's a problem with authentication. I use lighttpd also with pihole.

**Comment by mitchellurgero** [comment]
lighttpd needs to be able to run the files in the `app/bin` folder.

**Comment by mitchellurgero** [comment]
Also, you can use PHP's built in web server for this as well:
```
cd /var/www/html (Or where ever you put pivpn-gui)
php -S 0.0.0.0:8000
```

**Comment by polleke67** [comment]
sudo git clone https://github.com/mitchellurgero/pivpn-gui /var/www/html/pivpn-gui
sudo nano /etc/lighttpd/lighttpd.conf
# I added:
	# If the URL starts with /pivpn-gui, it is the Pi Open VPN Web interface
	$HTTP["url"] =~ "^/pivpn-gui/" {
	    # Create a response header for debugging using curl -I
	    setenv.add-response-header = (
	        "Pi-VPN" => "ThePi-VPN Web interface is working!",
	        "X-Frame-Options" => "DENY"
	    )
	}
# restarted lighttpd
sudo su
/etc/init.d/lighttpd restart


Now the the website responds when browsing http://192.168.62.70/pivpn-gui
It is asking for username/password, but pi/raspberry does not work. 
I finally got the error msg: Too many login attempts, please contact the system administrator.
Any idea?

**Comment by mitchellurgero** [comment]
the webserver needs to be running under a user with sudo access (so the script can check passwd and also run the pivpn tools) I recommend running the webserver under "pi" but make sure the pi is not accessible from the internet. This script has not been security audited.

Also if this is on a pi1 you MUST recompile pam.c into chkpasswd since chkpasswd binary was built for Pi2/3, not the pi1:
```
sudo apt install libpam0g-dev
cd app/bin
gcc -o chkpasswd pam.c -lpam -lpam_misc
```

**Comment by polleke67** [comment]
sudo apt install libpam0g-dev
cd /var/www/html/pivpn-gui/app/bin
gcc -o chkpasswd pam.c -lpam -lpam_misc
==> OK, both webpages accessible (192.168.62.70/admin and 192.168.62.70/pivpn-gui), but 192.168.62.70/pivpn-gui does not allow me to access it using pi/raspberry

sudo chown -R pi:pi /var/www/html
sudo service lighttpd stop
sudo sed -i 's/server\.username             \= \"www\-data\"/server\.username             \= \"pi\"/' /etc/lighttpd/lighttpd.conf
sudo sed -i 's/server\.groupname            \= \"www\-data\"/server\.groupname            \= \"pi\"/' /etc/lighttpd/lighttpd.conf
sudo sed -i 's/install \-d \-o www\-data \-g www\-data \-m 0750 \"\/var\/run\/lighttpd\"/install \-d \-o pi \-g pi \-m 0750 \"\/var\/run\/lighttpd\"/' /etc/init.d/lighttpd
sudo service lighttpd start
==> Both webpages not accessible (192.168.62.70/admin and 192.168.62.70/pivpn-gui)

**Comment by mitchellurgero** [comment]
Is the pi user configured to use sudo without password?

**Comment by mitchellurgero** [comment]
If you can show me error logs it would help a lot.

**Comment by polleke67** [comment]
pi@raspberrypi:/var/www/html/pivpn-gui/app/bin $ sudo tail -f /var/log/lighttpd/access.log
1537516575|192.168.62.70|GET /pivpn-gui/bower_components/jquery/dist/jquery.min.js HTTP/1.1|304|0
1537516575|192.168.62.70|GET /pivpn-gui/bower_components/bootstrap/dist/js/bootstrap.min.js HTTP/1.1|304|0
1537516575|192.168.62.70|GET /pivpn-gui/js/material.js HTTP/1.1|304|0
1537516575|192.168.62.70|GET /pivpn-gui/bower_components/metisMenu/dist/metisMenu.min.js HTTP/1.1|304|0
1537516575|192.168.62.70|GET /pivpn-gui/bower_components/raphael/raphael-min.js HTTP/1.1|304|0
1537516575|192.168.62.70|GET /pivpn-gui/bower_components/morrisjs/morris.min.js HTTP/1.1|304|0
1537516575|192.168.62.70|GET /pivpn-gui/js/morris-data.js HTTP/1.1|304|0
1537516575|192.168.62.70|GET /pivpn-gui/dist/js/sb-admin-2.js HTTP/1.1|304|0
1537562022|192.168.62.70|POST /pivpn-gui/index.php HTTP/1.1|200|4131
1537562022|192.168.62.70|GET /pivpn-gui/bower_components/bootstrap/dist/css/bootstrap.min.css HTTP/1.1|304|0
1537562023|192.168.62.70|GET /pivpn-gui/css/bootstrap-material-design.css HTTP/1.1|304|0

sudo tail -f /var/log/auth.log
Sep 21 20:37:44 raspberrypi sudo: pam_unix(sudo:auth): conversation failed
Sep 21 20:37:44 raspberrypi sudo: pam_unix(sudo:auth): auth could not identify password for [www-data]
Sep 21 20:37:44 raspberrypi sudo: www-data : command not allowed ; TTY=unknown ; PWD=/var/www/html/pivpn-gui ; USER=root ; COMMAND=/bin/bash ./app/scripts/listusers.sh
Sep 21 20:39:01 raspberrypi CRON[8395]: pam_unix(cron:session): session opened for user root by (uid=0)
Sep 21 20:39:01 raspberrypi CRON[8395]: pam_unix(cron:session): session closed for user root
Sep 21 20:40:01 raspberrypi CRON[8446]: pam_unix(cron:session): session opened for user root by (uid=0)
Sep 21 20:40:02 raspberrypi CRON[8446]: pam_unix(cron:session): session closed for user root


sudo chown -R pi:pi /var/www/html
sudo service lighttpd stop
sudo sed -i 's/server\.username             \= \"www\-data\"/server\.username             \= \"pi\"/' /etc/lighttpd/lighttpd.conf
sudo sed -i 's/server\.groupname            \= \"www\-data\"/server\.groupname            \= \"pi\"/' /etc/lighttpd/lighttpd.conf
sudo sed -i 's/install \-d \-o www\-data \-g www\-data \-m 0750 \"\/var\/run\/lighttpd\"/install \-d \-o pi \-g pi \-m 0750 \"\/var\/run\/lighttpd\"/' /etc/init.d/lighttpd
sudo service lighttpd start

Nothing added to the /var/log/lighttpd/access.log and /var/log/auth.log
user pi will go to sudo without password.

**Comment by mitchellurgero** [comment]
From the logs there it looks like lighttpd is not running as "pi:pi"

**Comment by polleke67** [comment]
OK had to chown some dirs

sudo chown -R pi:pi /var/log/lighttpd
sudo chown pi:pi /var/run/lighttpd
sudo chown -R pi:pi /var/cache/lighttpd/compress
sudo chown -R pi:pi /var/cache/lighttpd/upload

Working fine now!

**Comment by polleke67** [comment]
Concerning the above logs, it was before I made the changes to /etc/lighttpd/lighttpd.conf and /etc/init.d/lighttpd
After I made the changes and tried to access the PiVPN-GUI webpage, nothing was added to the logs.
When I made chown changes to the above folders (/var/log/lighttpd, /var/run/lighttpd and /var/cache/lighttpd), PiVPN GUI worked, I could create new users and successfully download the ovpn file. 
But when I rebooted the Pi, the webserver was not working anymore (not for PiHole, not for PiVPN-GUI....

**Comment by mitchellurgero** [comment]
PiVPN-GUI is not compatible with PiHole because of how PiHole runs, that said if you make a *new virtual host* specifically for PI-VPN it would work as expected.
